import { useEffect, useRef, useState } from 'react'
import { acceptForDisposal, DEMO_WASTE_FACILITY, completeDisposal, flagManufacturerDispute, recordDisposalEvidence, recordPhysicalDisposal, scheduleDisposal, verifyManufacturerReturn } from '../services/pharmacyService'
import './Manufacturer.css'

function CameraCapture({ label, returnRequest, user, profile, evidenceType, onCaptured }) {
  const videoRef = useRef(null)
  const streamRef = useRef(null)
  const [open, setOpen] = useState(false)
  const [cameraReady, setCameraReady] = useState(false)
  const [captured, setCaptured] = useState(null)
  const [error, setError] = useState('')
  async function openCamera() {
    setError(''); setOpen(true)
    try { streamRef.current = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' }, audio: false }); setCameraReady(true); if (videoRef.current) { videoRef.current.srcObject = streamRef.current; await videoRef.current.play() } } catch { setError('Camera permission is required to capture live evidence. Please allow camera access and try again.') }
  }
  function closeCamera() { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; setCameraReady(false); if (videoRef.current) videoRef.current.srcObject = null; setOpen(false) }
  function capture() { const canvas = document.createElement('canvas'); canvas.width = videoRef.current.videoWidth; canvas.height = videoRef.current.videoHeight; canvas.getContext('2d').drawImage(videoRef.current, 0, 0); setCaptured({ preview: canvas.toDataURL('image/jpeg', .82), capturedAt: new Date().toISOString() }); closeCamera() }
  async function save() { if (!captured) return; try { await recordDisposalEvidence({ returnRequest, evidenceType, capturedAt: captured.capturedAt, user, profile }); onCaptured(captured) } catch (actionError) { setError(actionError.message) } }
  useEffect(() => () => streamRef.current?.getTracks().forEach((track) => track.stop()), [])
  return <section className="evidence-panel"><p className="eyebrow">Live evidence</p><h3>{label}</h3><p>Capture a new live photo for batch {returnRequest.batchNumber} · {returnRequest.quantity} units.</p>{captured ? <><strong>✓ Photo captured</strong><small>Captured {new Date(captured.capturedAt).toLocaleString('en-IN')}</small><div className="evidence-actions"><button type="button" className="button secondary" onClick={() => { setCaptured(null); openCamera() }}>Retake</button><button type="button" className="button primary" onClick={save}>Continue</button></div></> : <button type="button" className="button secondary" onClick={openCamera}>Open camera</button>}{open && <div className="camera-modal"><video ref={videoRef} playsInline muted /><div><button type="button" className="button primary" onClick={capture} disabled={!cameraReady}>Capture live photo</button><button type="button" className="button secondary" onClick={closeCamera}>Cancel</button></div></div>}{error && <div className="form-alert error" role="alert">{error}</div>}</section>
}

export default function ManufacturerReturnDetailPage({ returnRequest, user, profile, navigate }) {
  const [batch, setBatch] = useState(returnRequest?.batchNumber || '')
  const [quantity, setQuantity] = useState(returnRequest?.receivedQuantity || returnRequest?.quantity || '')
  const [condition, setCondition] = useState('Sealed')
  const [notes, setNotes] = useState('')
  const facility = DEMO_WASTE_FACILITY
  const [disposalDate, setDisposalDate] = useState('')
  const [disposalTimeWindow, setDisposalTimeWindow] = useState('')
  const [disposalReference, setDisposalReference] = useState('')
  const [disposalNotes, setDisposalNotes] = useState('')
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [localEvidence, setLocalEvidence] = useState({})
  const [disposalRecorded, setDisposalRecorded] = useState(Boolean(returnRequest?.disposalRecordedAt))
  if (!returnRequest) return <div className="loading-panel error-panel"><strong>Return not found.</strong><button type="button" className="button secondary" onClick={() => navigate('/manufacturer/returns')}>Back to returns</button></div>
  const expected = Number(returnRequest.quantity)
  const received = Number(quantity)
  const difference = received - expected
  const manufacturerVerified = ['ACCEPTED_FOR_DISPOSAL', 'DISPOSAL_SCHEDULED', 'DISPOSAL_IN_PROGRESS', 'AFTER_DISPOSAL_EVIDENCE_CAPTURED', 'DISPOSAL_COMPLETED', 'DESTROYED'].includes(returnRequest.status) || Boolean(returnRequest.manufacturerVerificationStatus === 'VERIFIED')
  const canAccept = returnRequest.status === 'RECEIVED' && batch.trim() === returnRequest.batchNumber && difference === 0
  const canMoveToDisposal = Boolean(returnRequest.manufacturerVerificationStatus === 'VERIFIED' || returnRequest.manufacturerVerifiedQuantity || returnRequest.manufacturerReceivedQuantity)
  const beforeCaptured = Boolean(returnRequest.beforeDisposalEvidence || localEvidence.BEFORE_DISPOSAL)
  const afterCaptured = Boolean(returnRequest.afterDisposalEvidence || localEvidence.AFTER_DISPOSAL)

  async function run(action) { setBusy(true); setError(''); setMessage(''); try { await action(); setMessage('Shared return record updated.') } catch (actionError) { setError(actionError.message) } finally { setBusy(false) } }
  function accept() { return run(() => verifyManufacturerReturn({ returnRequest, receivedBatchNumber: batch, receivedQuantity: quantity, condition, notes, user, profile })) }
  function acceptDisposal() { return run(() => acceptForDisposal({ returnRequest, user, profile })) }
  function dispute() { return run(() => flagManufacturerDispute({ returnRequest, receivedBatchNumber: batch, receivedQuantity: quantity, reason: batch.trim() !== returnRequest.batchNumber ? 'Batch mismatch' : 'Quantity mismatch', notes, user, profile })) }
  function schedule() { return run(() => scheduleDisposal({ returnRequest, facility, disposalDate, disposalTimeWindow, disposalReference, notes: disposalNotes, user, profile })) }
  function complete() { return run(() => completeDisposal({ returnRequest, user, profile })) }
  function recordDisposal() { return run(async () => { await recordPhysicalDisposal({ returnRequest, user, profile }); setDisposalRecorded(true) }) }
  const disposalSteps = [
    ['Manufacturer verification', manufacturerVerified],
    ['Accepted for disposal', ['ACCEPTED_FOR_DISPOSAL', 'DISPOSAL_SCHEDULED', 'DISPOSAL_IN_PROGRESS', 'AFTER_DISPOSAL_EVIDENCE_CAPTURED', 'DISPOSAL_COMPLETED', 'DESTROYED'].includes(returnRequest.status)],
    ['Waste facility selected', Boolean(returnRequest.wasteFacilityId)],
    ['Disposal scheduled', Boolean(returnRequest.disposalScheduledAt)],
    ['Before-disposal evidence', beforeCaptured],
    ['Physical disposal', Boolean(returnRequest.disposalRecordedAt || disposalRecorded)],
    ['After-disposal evidence', afterCaptured],
    ['Complete disposal', ['DISPOSAL_COMPLETED', 'DESTROYED'].includes(returnRequest.status)],
  ]
  return <div className="page-stack manufacturer-page"><div className="page-heading"><div><p className="eyebrow">Manufacturer return detail</p><h1>{returnRequest.medicineName} {returnRequest.strength}</h1><p className="page-subtitle">Batch {returnRequest.batchNumber} · Shared reverse-chain record</p></div><button type="button" className="button secondary" onClick={() => navigate('/manufacturer/returns')}>← Incoming returns</button></div>{message && <div className="inline-message success" role="status">{message}</div>}{error && <div className="inline-message error" role="alert">{error}</div>}
    <section className="panel disposal-progress-panel"><div className="panel-heading"><div><p className="eyebrow">Disposal workflow</p><h2>Track this batch</h2></div><span className="manufacturer-status">{returnRequest.status.replaceAll('_', ' ')}</span></div><div className="disposal-step-list">{disposalSteps.map(([label, complete]) => <div className={complete ? 'disposal-step complete' : 'disposal-step'} key={label}><span aria-hidden="true">{complete ? '✓' : '○'}</span><strong>{label}</strong></div>)}</div></section>
    <section className="panel manufacturer-detail-panel"><div className="panel-heading"><div><p className="eyebrow">Section 1</p><h2>Pharmacy record</h2></div><span className="comparison-label">READ ONLY</span></div><div className="trace-grid"><span><small>Pharmacy</small><strong>{returnRequest.pharmacyId}</strong></span><span><small>Medicine</small><strong>{returnRequest.medicineName} {returnRequest.strength}</strong></span><span><small>Batch</small><strong>{returnRequest.batchNumber}</strong></span><span><small>Declared quantity</small><strong>{expected} units</strong></span><span><small>Reason</small><strong>{returnRequest.reason}</strong></span><span><small>Source</small><strong>{returnRequest.source || 'MANUAL'}</strong></span></div></section>
    <section className="panel manufacturer-detail-panel"><div className="panel-heading"><div><p className="eyebrow">Section 2</p><h2>Distributor verification</h2></div><span className="comparison-label">READ ONLY</span></div><div className="trace-grid"><span><small>Distributor</small><strong>{returnRequest.distributorName || returnRequest.distributorId || 'Distributor'}</strong></span><span><small>Collector</small><strong>{returnRequest.collectorName || returnRequest.assignedPerson || 'Not recorded'}</strong></span><span><small>Pickup reference</small><strong>{returnRequest.pickupReference || 'Not recorded'}</strong></span><span><small>Status</small><strong>{returnRequest.status.replaceAll('_', ' ')}</strong></span><span><small>Expected quantity</small><strong>{expected} units</strong></span><span><small>Distributor received</small><strong>{returnRequest.receivedQuantity ?? 'Not recorded'} units</strong></span></div></section>
    {returnRequest.status === 'RECEIVED' && <section className="panel manufacturer-detail-panel"><div className="panel-heading"><div><p className="eyebrow">Section 3</p><h2>Manufacturer verification</h2></div><span className="comparison-label">INPUT</span></div><form className="manufacturer-form"><label>Manufacturer received batch<input value={batch} onChange={(event) => setBatch(event.target.value)} placeholder={returnRequest.batchNumber} /></label><label>Manufacturer received quantity<input type="number" min="0" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><label>Condition<select value={condition} onChange={(event) => setCondition(event.target.value)}><option>Sealed</option><option>Damaged</option><option>Other</option></select></label><label>Verification notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Optional notes" /></label>{batch && batch !== returnRequest.batchNumber && <div className="verification-warning">Expected: {returnRequest.batchNumber} · Received: {batch} · BATCH MISMATCH</div>}{difference !== 0 && <div className="verification-warning">QUANTITY DISCREPANCY · Difference: {Math.abs(difference)} units</div>}<div className="verification-actions"><button type="button" className="button primary" disabled={!canAccept || busy} onClick={accept}>Accept return</button><button type="button" className="button secondary" disabled={busy || (batch === returnRequest.batchNumber && difference === 0)} onClick={dispute}>Flag discrepancy</button></div></form></section>}
    {manufacturerVerified && <section className="panel manufacturer-detail-panel"><div className="panel-heading"><div><p className="eyebrow">Section 3</p><h2>Manufacturer verified</h2></div><span className="manufacturer-status">{returnRequest.status.replaceAll('_', ' ')}</span></div><div className="trace-grid"><span><small>Received batch</small><strong>{returnRequest.manufacturerReceivedBatchNumber || returnRequest.batchNumber}</strong></span><span><small>Received quantity</small><strong>{returnRequest.manufacturerReceivedQuantity || expected} units</strong></span><span><small>Facility</small><strong>{returnRequest.wasteFacilityName || 'Not scheduled'}</strong></span></div>{canMoveToDisposal && <div className="verification-actions"><button type="button" className="button primary" disabled={busy || returnRequest.status === 'ACCEPTED_FOR_DISPOSAL'} onClick={acceptDisposal}>Accept for disposal</button></div>}</section>}
    {returnRequest.status === 'ACCEPTED_FOR_DISPOSAL' && <section className="panel disposal-panel"><div className="panel-heading"><div><p className="eyebrow">Disposal workflow</p><h2>Select authorized waste facility</h2></div></div><div className="facility-card"><strong>{facility.name}</strong><span>Authorization: {facility.authorizationStatus}</span><small>Facility ID: {facility.id}</small></div><form className="manufacturer-form"><label>Disposal date<input type="date" value={disposalDate} onChange={(event) => setDisposalDate(event.target.value)} /></label><label>Disposal time/window<input value={disposalTimeWindow} onChange={(event) => setDisposalTimeWindow(event.target.value)} placeholder="10:00 - 12:00" /></label><label>Disposal reference<input value={disposalReference} onChange={(event) => setDisposalReference(event.target.value)} placeholder="DISP-2026-0042" /></label><label>Notes<textarea value={disposalNotes} onChange={(event) => setDisposalNotes(event.target.value)} /></label><button type="button" className="button primary" disabled={busy || !disposalDate || !disposalReference} onClick={schedule}>Schedule disposal</button></form></section>}
    {['DISPOSAL_SCHEDULED', 'DISPOSAL_IN_PROGRESS', 'AFTER_DISPOSAL_EVIDENCE_CAPTURED'].includes(returnRequest.status) && <section className="panel disposal-panel"><div className="panel-heading"><div><p className="eyebrow">Disposal workflow</p><h2>Disposal in progress</h2></div><span className="manufacturer-status">{returnRequest.status.replaceAll('_', ' ')}</span></div><div className="trace-grid"><span><small>Facility</small><strong>{returnRequest.wasteFacilityName}</strong></span><span><small>Reference</small><strong>{returnRequest.disposalReference}</strong></span><span><small>Quantity</small><strong>{expected} units</strong></span></div><div className="evidence-grid">{!beforeCaptured && <CameraCapture label="Before-disposal evidence" returnRequest={returnRequest} user={user} profile={profile} evidenceType="BEFORE_DISPOSAL" onCaptured={(evidence) => setLocalEvidence((current) => ({ ...current, BEFORE_DISPOSAL: evidence }))} />}{beforeCaptured && <div className="evidence-panel complete"><strong>✓ Before-disposal evidence captured</strong><span>Live evidence metadata recorded for this batch.</span></div>}{beforeCaptured && !disposalRecorded && <div className="physical-disposal-note"><strong>Record the physical disposal</strong><span>PharmaLoop records this workflow; the authorized facility performs the physical disposal.</span><button type="button" className="button secondary" onClick={recordDisposal} disabled={busy}>Disposal recorded</button></div>}{beforeCaptured && disposalRecorded && !afterCaptured && <CameraCapture label="After-disposal evidence" returnRequest={returnRequest} user={user} profile={profile} evidenceType="AFTER_DISPOSAL" onCaptured={(evidence) => setLocalEvidence((current) => ({ ...current, AFTER_DISPOSAL: evidence }))} />}{beforeCaptured && disposalRecorded && afterCaptured && <div className="complete-checklist"><strong>DISPOSAL READY TO COMPLETE</strong><span>✓ Manufacturer verification</span><span>✓ Facility assigned</span><span>✓ Before-disposal evidence</span><span>✓ Disposal recorded</span><span>✓ After-disposal evidence</span><button type="button" className="button primary" onClick={complete} disabled={busy}>Complete disposal</button></div>}</div></section>}
    {['DISPOSAL_COMPLETED', 'DESTROYED'].includes(returnRequest.status) && <section className="panel disposal-panel"><div className="complete-checklist"><strong>✓ BATCH DESTROYED / CLOSED</strong><span>Disposal completed and certificate generated.</span><button type="button" className="button primary" onClick={() => navigate('/manufacturer/certificates')}>View certificates</button></div></section>}
  </div>
}
