import { useState } from 'react'
import { logOut } from '../services/pharmacyService'
import AssistantPanel from './AssistantPanel'

const links = [{ path: '/distributor/dashboard', label: 'Overview', icon: 'grid' }, { path: '/distributor/returns', label: 'Incoming returns', icon: 'return' }]
function Icon({ type }) { const shapes = { grid: <><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></>, return: <><path d="M20 7H7M7 7l4-4M7 7l4 4M4 17h13M17 17l-4-4M17 17l-4 4" /></> }; return <svg className="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true">{shapes[type]}</svg> }

export default function DistributorShell({ user, profile, route, navigate, pendingCount, assistantData, children }) {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [loggingOut, setLoggingOut] = useState(false)
  async function logout() { setLoggingOut(true); try { await logOut(); navigate('/distributor/login') } finally { setLoggingOut(false) } }
  return <div className="app-frame distributor-frame"><aside className={`sidebar ${mobileOpen ? 'sidebar-open' : ''}`}><div className="brand-lockup"><div className="brand-mark">P</div><div><strong>PharmaLoop</strong><span>Distributor operations</span></div></div><div className="sidebar-label">Workspace</div><nav className="primary-nav" aria-label="Distributor navigation">{links.map((link) => <button className={route === link.path ? 'nav-item active' : 'nav-item'} key={link.path} type="button" onClick={() => { navigate(link.path); setMobileOpen(false) }}><Icon type={link.icon} />{link.label}{link.path.endsWith('returns') && pendingCount > 0 && <span className="nav-count">{pendingCount}</span>}</button>)}</nav><div className="sidebar-footer"><div className="sidebar-note"><span className="status-dot" /><span><strong>Distributor workspace</strong><small>Firestore synced</small></span></div><button type="button" className="logout-button" onClick={logout} disabled={loggingOut}>↪ {loggingOut ? 'Signing out...' : 'Sign out'}</button></div></aside>{mobileOpen && <button type="button" className="mobile-scrim" aria-label="Close menu" onClick={() => setMobileOpen(false)} />}<main className="main-area"><header className="topbar"><button type="button" className="mobile-menu" aria-label="Open menu" onClick={() => setMobileOpen(true)}><span className="windows-menu-icon" aria-hidden="true"><i /><i /><i /><i /></span></button><div className="breadcrumb">Distributor workspace <span>/</span> {route.includes('returns') ? 'Incoming returns' : 'Overview'}</div><div className="topbar-actions"><AssistantPanel {...assistantData} /><div className="topbar-user"><div className="avatar">{(profile?.name || user?.email || 'D').slice(0, 1).toUpperCase()}</div><div><strong>{profile?.name || 'Distributor team'}</strong><span>{profile?.distributorName || 'Apollo Distribution Hub'}</span></div></div></div></header><div className="page-content">{children}</div></main></div>
}
